---

- name: Install Dnsmasq package
  apt:
    name: dnsmasq
    state: present
  tags: dnsmasq, installation

- name: Enable dnsmasq service
  service:
    name: dnsmasq
    enabled: true
  tags: dnsmasq

- name: Create Dnsmasq configuration
  template:
    src: dnsmasq-10-consul.j2
    dest: /etc/dnsmasq.d/10-consul
    owner: root
    group: root
    mode: 0644
  notify: restart dnsmasq
  tags: dnsmasq