---

- name: Create SSL directory
  file:
    dest: "{{ consul_tls_dir }}"
    state: directory
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0755

- name: Copy CA certificate
  copy:
    src: "{{ consul_tls_src_files }}/{{ consul_tls_ca_crt }}"
    dest: "{{ consul_tls_dir }}/{{ consul_tls_ca_crt }}"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0644

- name: Copy server certificate
  copy:
    src: "{{ consul_tls_src_files }}/{{ consul_tls_crt }}"
    dest: "{{ consul_tls_dir }}/{{ consul_tls_crt }}"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0644

- name: Copy server key
  copy:
    src: "{{ consul_tls_src_files }}/{{ consul_tls_key }}"
    dest: "{{ consul_tls_dir }}/{{ consul_tls_key }}"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0600
